# str_message/__init__.py
import pathlib

from ._message import (
    ALL_MESSAGE_TYPES,
    ANY_MESSAGE_TYPES,
    CONTENT_AUDIO_EXPR,
    CONTENT_FILE_FILENAME_EXPR,
    CONTENT_FILE_ID_EXPR,
    CONTENT_FILE_URL_EXPR,
    CONTENT_IMAGE_ID_EXPR,
    CONTENT_IMAGE_URL_EXPR,
    OPENAI_MESSAGE_PARAM_TYPES,
    OPENAI_MESSAGE_TYPES,
    AssistantMessage,
    DeveloperMessage,
    ListFuncDefAdapter,
    Message,
    MessageTypes,
    ReasoningMessage,
    ResponseInputItemAdapter,
    ResponseInputItemModels,
    SystemMessage,
    ToolCallMessage,
    ToolCallOutputMessage,
    UserMessage,
)

__version__ = pathlib.Path(__file__).parent.joinpath("VERSION").read_text().strip()

__all__ = [
    "ALL_MESSAGE_TYPES",
    "ALL_MESSAGE_TYPES",
    "ANY_MESSAGE_TYPES",
    "AssistantMessage",
    "CONTENT_AUDIO_EXPR",
    "CONTENT_FILE_URL_EXPR",
    "CONTENT_FILE_FILENAME_EXPR",
    "CONTENT_FILE_ID_EXPR",
    "CONTENT_IMAGE_URL_EXPR",
    "CONTENT_IMAGE_ID_EXPR",
    "DeveloperMessage",
    "ListFuncDefAdapter",
    "ListFuncDefAdapter",
    "Message",
    "MessageTypes",
    "OPENAI_MESSAGE_PARAM_TYPES",
    "OPENAI_MESSAGE_TYPES",
    "ReasoningMessage",
    "ResponseInputItemAdapter",
    "ResponseInputItemModels",
    "SystemMessage",
    "ToolCallMessage",
    "ToolCallOutputMessage",
    "UserMessage",
]
